id: A4C092EB9
base_file: fE24B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:38:44.700839
  last_modified_at: 2022-05-30 20:38:44.700849
